# These are supported funding model platforms

github: quiple
patreon: quiple
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
otechie:
lfx_crowdfunding:
custom: ['https://toss.me/quiple', 'https://qr.kakaopay.com/Ej8JN15fH']
