page_title: Galmuri
description: 닌텐도 DS에 사용된 비트맵 폰트를 기반으로 한 픽셀풍 윤곽선 폰트
enable_smart_app_banner: false
url: https://galmuri.quiple.dev
baseurl: /
your_name: Lee Minseo (Quiple)
email_address: itoupluk427@gmail.com
twitter_username: kuipuru
github_username: quiple

remote_theme: emilbaehr/automatic-app-landing-page
sass:
  style: :compressed
exclude:
  - LICENSE
  - README.md
  - CNAME
collections:
  pages:
    output: true
    permalink: /:path/
markdown: kramdown
