title: 갈무리
description: 닌텐도 DS에 사용된 비트맵 폰트를 기반으로 한 픽셀풍 윤곽선 폰트.
language: 'ko-kr'
owner_name: 'Lee Minseo (Quiple)'
theme: jekyll-theme-minimal
zip_url: 'https://github.com/quiple/galmuri/archive/refs/heads/main.zip'
