title: 갈무리
description: 닌텐도 DS에 사용된 비트맵 폰트를 기반으로 한 픽셀풍 윤곽선 폰트
language: ko-KR
url: https://quiple.github.io
baseurl: /galmuri
repository: quiple/galmuri
owner_name: Lee Minseo (Quiple)

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

remote_theme: emilbaehr/automatic-app-landing-page
sass:
  style: :compressed
exclude:
  - LICENSE
  - README.md
  - CNAME
collections:
  pages:
    output: true
    permalink: /:path/
markdown: kramdown
