name: Distribution

on:
  push:
    paths:
      - 'src/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '18'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Set up Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32
      - name: Clean up Distribution Files
        run: |
          rm -rf ./dist/*.bdf
          rm -rf ./dist/*.ttf
      - name: Convert to BDF Font
        run: |
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o ./dist/Galmuri11.bdf ./src/Galmuri11.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o ./dist/Galmuri11-Bold.bdf ./src/Galmuri11-Bold.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o ./dist/Galmuri9.bdf ./src/Galmuri9.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o ./dist/Galmuri7.bdf ./src/Galmuri7.kbits
      - name: Convert to TrueType Font
        run: |
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o ./dist/Galmuri11.ttf ./src/Galmuri11.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o ./dist/Galmuri11-Bold.ttf ./src/Galmuri11-Bold.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o ./dist/Galmuri9.ttf ./src/Galmuri9.kbits
          java -jar ./bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o ./dist/Galmuri7.ttf ./src/Galmuri7.kbits

      - name: Convert BDF Font
        run: |
          python ./files/fix-yAxis.py ./dist/Galmuri11.bdf ./dist/g11_mod.bdf
          python ./files/fix-yAxis.py ./dist/Galmuri11-Bold.bdf ./dist/g11b_mod.bdf
          python ./files/fix-yAxis.py ./dist/Galmuri9.bdf ./dist/g9_mod.bdf
          python ./files/fix-yAxis.py ./dist/Galmuri7.bdf ./dist/g7_mod.bdf
      - name: Convert to TrueType Font
        run: |
          wine ./files/bdf2ttf.exe ./dist/Galmuri11Bitmap.ttf ./files/g11.ini ./dist/g11_mod.bdf
          wine ./files/bdf2ttf.exe ./dist/Galmuri11Bitmap-Bold.ttf ./files/g11b.ini ./dist/g11b_mod.bdf
          wine ./files/bdf2ttf.exe ./dist/Galmuri9Bitmap.ttf ./files/g9.ini ./dist/g9_mod.bdf
          wine ./files/bdf2ttf.exe ./dist/Galmuri7Bitmap.ttf ./files/g7.ini ./dist/g7_mod.bdf
      - name: Clean up Temporary Files
        run: del ./dist/g11_mod.bdf ./dist/g11b_mod.bdf ./dist/g9_mod.bdf ./dist/g7_mod.bdf

      - name: Commit Changed Files
        uses: stefanzweifel/git-auto-commit-action@v4
