name: release

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Set up fontTools
        run: pip install fonttools[woff]

      - name: Set up AFDKO
        run: pip install --user afdko

      - name: Set up Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 86B72ED9
          sudo add-apt-repository "deb [arch=amd64] https://mirror.mxe.cc/repos/apt focal main"
          sudo apt-get -qq update
          sudo apt-get install -y --allow-downgrades libpcre2-8-0=10.34-7
          sudo apt-get install -y wine32

      - name: Clean up distribution files
        run: |
          rm -rf dist/*.bdf
          rm -rf dist/*.ttf
          rm -rf dist/*.woff2

      - name: Convert to BDF fonts and convert to TrueType bitmap fonts
        run: |
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri11.bdf src/Galmuri11.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri11-Bold.bdf src/Galmuri11-Bold.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri9.bdf src/Galmuri9.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f bdf -o dist/Galmuri7.bdf src/Galmuri7.kbits
          python files/fix-yAxis.py dist/Galmuri11.bdf dist/g11_mod.bdf
          python files/fix-yAxis.py dist/Galmuri11-Bold.bdf dist/g11b_mod.bdf
          python files/fix-yAxis.py dist/Galmuri9.bdf dist/g9_mod.bdf
          python files/fix-yAxis.py dist/Galmuri7.bdf dist/g7_mod.bdf
          wine files/bdf2ttf.exe dist/Galmuri11Bitmap.ttf files/g11.ini dist/g11_mod.bdf
          wine files/bdf2ttf.exe dist/Galmuri11Bitmap-Bold.ttf files/g11b.ini dist/g11b_mod.bdf
          wine files/bdf2ttf.exe dist/Galmuri9Bitmap.ttf files/g9.ini dist/g9_mod.bdf
          wine files/bdf2ttf.exe dist/Galmuri7Bitmap.ttf files/g7.ini dist/g7_mod.bdf

      - name: Convert to TrueType fonts and compress to WOFF2
        run: |
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri11.ttf src/Galmuri11.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri11-Bold.ttf src/Galmuri11-Bold.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri9.ttf src/Galmuri9.kbits
          java -jar bitsnpicas/downloads/BitsNPicas.jar convertbitmap -f ttf -o tGalmuri7.ttf src/Galmuri7.kbits
          makeotf -mf files/FontMenuNameDB -f tGalmuri11.ttf -ff files/g11.fea -o dist/Galmuri11.ttf -osbOn 6 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri11-Bold.ttf -ff files/g11b.fea -o dist/Galmuri11-Bold.ttf -osbOn 5 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri9.ttf -ff files/g9.fea -o dist/Galmuri9.ttf -osbOn 6 -addn
          makeotf -mf files/FontMenuNameDB -f tGalmuri7.ttf -ff files/g7.fea -o dist/Galmuri7.ttf -osbOn 6 -addn
          fonttools ttLib.woff2 compress dist/Galmuri11.ttf
          fonttools ttLib.woff2 compress dist/Galmuri11-Bold.ttf
          fonttools ttLib.woff2 compress dist/Galmuri9.ttf
          fonttools ttLib.woff2 compress dist/Galmuri7.ttf

      - name: Update npm package version
        run: |
          python files/version.py files/g11.fea package.json
          python files/version.py files/g11.fea package-lock.json

      - name: Get npm package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Make zip
        run: zip -r Galmuri-v${{ steps.package-version.outputs.current-version }}.zip dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Galmuri-v${{ steps.package-version.outputs.current-version }}.zip
          tag_name: 'v${{ steps.package-version.outputs.current-version }}'

      - name: Clean up Temporary Files
        run: |
          rm -rf dist/*_mod.bdf
          rm -rf Galmuri-v*.zip
          rm -rf tGalmuri*.ttf

      - name: Publish to npm
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
